repos:
  - repo: local
    hooks:
      - id: pytest-commit
        name: Test with pytest
        entry: pytest
        language: system
        pass_filenames: false
        stages: [commit]

      - id: pytest-push
        name: Test with pytest
        entry: pytest
        language: system
        pass_filenames: false
        stages: [push]
        args:
          - "--cov-fail-under=85"

      - id: mypy
        name: Check types with mypy
        entry: mypy
        language: system
        pass_filenames: true
        types: [python]
        stages: [commit, push]

      - id: black
        name: Format with black
        entry: black
        language: system
        pass_filenames: true
        types: [python]
        stages: [commit, push]

      - id: flake8
        name: Check formatting with flake8
        entry: flake8
        language: system
        pass_filenames: true
        types: [python]
        stages: [commit, push]
