name: CI/CD

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install poetry
        uses: snok/install-poetry@v1.2.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Run unit tests
        run: poetry run pytest

      - name: Format code with black
        run: poetry run black server

      - name: Analyse code with flake8
        run: poetry run flake8 server

      - name: Analyse code with mypy
        run: poetry run mypy server

      - name: Analyse the code with pylint
        run: poetry run pylint server

  build:
    needs: [test]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login on DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/websocket-test:${{ github.run_id }}
            ${{secrets.DOCKERHUB_USERNAME}}/websocket-test:latest
          github-token: ${{ github.token }}

  deploy:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: caprover-releases

      - name: Set captain-definition new image
        uses: jossef/action-set-json-field@v1
        with:
          file: captain-definition
          field: imageName
          value: ${{secrets.DOCKERHUB_USERNAME}}/websocket-test:${{ github.run_id }}

      - name: Commit new captain-definition
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: update image tag to ${{ github.run_id }}
          branch: caprover-releases
          push_options: --force
