name: Code Analysis

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --global poetry
          poetry install

      - name: Formatting code with black
        run: |
          black server

      - name: Analysing code with flake8
        run: |
          flake8 server

      - name: Analysing code with mypy
        run: |
          mypy server

      - name: Analysing the code with pylint
        run: |
          pylint server
